### ISSUE TITLE
Pausing in the Snake Room in Lost World is Prone to Crashing

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#117]
Just what the title says. Not sure if it's a problem on my end, but I've made it happen a couple times, now. I head left, skip the first water switch, and drop down to the ground to continue on to the first door switch. I pause just before the spikes, and....it crashes. No idea what could be causing it.
![crash sondicoot](https://cloud.githubusercontent.com/assets/26051785/25080598/fa469cde-230a-11e7-9c9e-c24d66fdcc05.png)

**Comment by Zetchzie** [comment]
Shit that does happen I wonder what happened. Does it happen without your fixes?

**Comment by PiKeyAr** [comment]
This was happening because SADX's function to animate the water in the snake room was still running even when the game was paused (without actually updating the model), which overrode my animation that was running only when the game wasn't paused. I've uploaded an update which should fix that, but there may be other areas like that so please report issues if you run into any.

**Comment by supercoolsonic** [comment]
I've tried this with nearly every animating body of water in the game. If someone could test the water in the Past Adventure Fields, that'd be great. Also, the water that appears in both rooms that Gamma can enter on the inside of the Egg Carrier, the ones where he gets his upgrades. If the game doesn't crash on any of those, then I'd say this problem does not occur anywhere else, and this can be closed.

**Comment by PiKeyAr** [comment]
The snake room water is a little special because it isn't a landtable object (unlike, say, Station Square sewer water or water in the Past with SA1 textures), and there's a special function to animate it. Furthermore, the bug is very specific because the code was setting different texture IDs that were outside the boundaries of the Dreamcast PVMs, which often isn't the case. The only similar objects I can remember off the top of my head are Suimen objects in Hot Shelter and the Egg Carrier pool water, but those use separate PVMs for their textures, so they should be fine.
