### ISSUE TITLE
Minor Texture Issue in MR with Latest Dreamcast PVM

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#124]
Hi. With the object Dreamcast PVM file, I noticed there's a slight problem with the monkey cage now.
![mystic ruins light texture issue](https://cloud.githubusercontent.com/assets/26051785/25557421/8e017d98-2cd6-11e7-8891-fd0a381c24c9.png)

Oh, and, uhhh....
http://www.megafileupload.com/1qlie/Broken_Stand.png
Ummm.....I know....you probably don't care about this, but....would you consider fixing it? The textures? Pretty please? This happened with a couple other 'special' objects in other levels, but I didn't say anything because I thought you'd think it doesn't matter.

If anyone is wondering how progress is going with SET Fixes, college got real recently and has been eating up a lot of time, but I've still managed to get some things done and will have a few fixes ready soon.

**Comment by PiKeyAr** [comment]
I've fixed the light and probably the item stand too, but I'm not sure since it's an object that doesn't show up in my layouts.
The reason such things happen is that I'm currently switching all object textures to original Dreamcast textures, which aren't mirrored, therefore all models that use mirrored textures in SADX need to be replaced with their Dreamcast counterparts to look properly. It is a rather involved process of finding which objects are affected, locating their models in both SA1 and SADX, and then making sure they are properly replaced, which can also get complicated if it's an object with movement or animations.
If any of the affected objects happen to be unused in the game, then yeah, I don't really care much about them, so this item stand thing is probably the only exception I'm gonna make for the time being.

**Comment by supercoolsonic** [comment]
Awesome! Both are fixed. I thought that might be the case as to why some others started having their textures appear oddly. ....Which is weird, because that must mean they actually went and worked with that object to change it to use mirrored textures. ...Or maybe it was a process that effected a large amount of things without them knowing. Well, thanks for fixing them.
