### ISSUE TITLE
Emerald Coast 1 water plane Y adjustment

### ISSUE THREAD

**Issue by Rayray-Alcard** [PiKeyAr/sadx_dreamcast#148]
White Ripples are above the water before and after wave effect just only in Act 1.
![27512766-9bcc0ca2-591a-11e7-8e63-7a5efaeb7726](https://user-images.githubusercontent.com/27602092/27577863-2ede4e02-5af0-11e7-9e0a-096ad39e7b3f.png)
![27512767-9e059e20-591a-11e7-9b16-5438a6fd40a3](https://user-images.githubusercontent.com/27602092/27577867-30977142-5af0-11e7-9c24-93bcc687359d.png)
It's the white circles texture surrounding Sonic and Tails above blue water.
Looked into the rest of the levels and water ripples look properly aligned
’less I missed something.

**Comment by PiKeyAr** [comment]
All Emerald Coast ocean models are rendered using functions with queued model flags to avoid rendering issues with the shoreline and the wave effect, as well as to allow proper lighting. Those queued flags cause minor issues such as water ripples being displayed below or the footprints and shadows being rendered above water. There is no good combination of functions/flags that would work with everything due to alpha sorting limitations. See #42.

**Comment by PiKeyAr** [comment]
Should be fixed in 0.9985

**Comment by Rayray-Alcard** [comment]
1) Great! Beginning area is fixed.
But some areas still have high Y alignment starting around the umbrella.
![screenshot_20170629073525](https://user-images.githubusercontent.com/27602092/27687077-673174dc-5ca3-11e7-9c03-efdb10f594b8.png)
Notice where Tails is at is the end of the fixed alignment area. The rest of the areas throughout the 1st act alignment look higher than the water by a very small amount but not as noticeable as it was. So much better than before.

2) I found the ripple texture itself looks sharper in Dreamcast. Can only see whilst moving yourself around and not able see it whilst standing still.
![untitled](https://user-images.githubusercontent.com/27602092/27687423-c902f1ee-5ca4-11e7-848f-463d9bdd6554.jpg)
Screenshot taken from Demul but looks like that on hardware too.

3) There is a shadow effect on a large plank right before the checkpoint at mark 8:57.
![untitled2](https://user-images.githubusercontent.com/27602092/27688722-9c9e008a-5ca9-11e7-92e4-05995ea0284c.png)
https://youtu.be/m1CwBvUvUwo?t=8m57s

He used VGA to HDMI. I use red/yellow/white composite cables and still see it. >.> Is it a fog or PL thing or could it be the Dreamcast console’s actual doing? Odd that the shadow cannot be seen on Dreamcast emulators and never on DX.

**Comment by PiKeyAr** [comment]
I've moved all water planes by -1.5 units, so that should fix everything. Anyway that's as much as I can do about it.

The ripple cannot be restored at the moment because the location of its model is unknown in SA1. The UVs are different between the SA1 and SADX versions of the object so a simple texture edit wouldn't work.

As for (3), it looks more like a rendering artifact rather than an intentional effect, I have no interest to recreate it.

**Comment by PiKeyAr** [comment]
The water ripple has been restored, so I'm marking this as resolved.
