### ISSUE TITLE
Tornado Gate Texture Lighting?

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#150]
So Tail's Tornado Gate model has been restored but we still have the lighting error on a little part of the model.
Here's 2 examples http://i.imgur.com/MbsxXOc.png
this also happens during night time, i'll assume this haven't been palettized.

**Comment by PiKeyAr** [comment]
It looks fine with the API branch of the lighting mod, but I fixed it just in case. This is related to material colors rather than lighting. Anyway it should be fixed whenever the next Mystic Ruins update drops. There are some technical issues with the server now so it will be uploaded when it's back up again.

**Comment by PiKeyAr** [comment]
The Mystic Ruins update should be working now.
