### ISSUE TITLE
Mod installer discussion

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#151]
**SADX Mod Installer by PkR**

[Features and changelog](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/installer.txt)

The latest version is always available [here](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/sadx_setup.exe).

**Comment by spookmeman** [comment]
I just tested it on my Steam install and it works, but it only uses 1.0 of the Lantern mod

**Comment by PiKeyAr** [comment]
It's supposed to download version 1.2.5 from my server, but if you run it from the same folder where you have sadx-dc-lighting.7z it will install that instead.

**Comment by PiKeyAr** [comment]
I'm closing this since it doesn't look like there will be much discussion. Feel free to reopen this if you run into any issues with the installer.

**Comment by PiKeyAr** [comment]
New features in Build 2:

- New UI
- Ability to set up resolution and several other Mod Loader settings (picked up from the ini or autodetected)
- Optimal mod configuration now auto-selected depending on what type of SADX install is detected
- Added more checks and warnings for various install scenarios
- The installer now deletes previous versions of checked mods if detected

New features in Build 3:
- Renamed to "SADX Mod Loader Setup"
- Added several new mods
- Rearranged components and defaults
- Added detailed descriptions for all components
- The installer now checks for pre-downloaded files in the "data" folder instead of the installer's folder
- DirectX and .NET installers are now also downloaded instead of being included in the installer
- The d3d8to9 shim required by the Lantern Engine mod is now also downloaded instead of being included in the installer
- Ability to retry failed downloads
- Server-side folder structure was accommodated for the above change
- Suppressed some unnecessary file copy dialogs
- Tool usage optimized for maximum use of the data folder and minimum access to the SADX folder
- Detects if BetterSADX is installed and removes incompatible mods
- Cleans up old versions of DC mods

**Comment by Omega247Gamma** [comment]
I have the STEAM version and I receive an error halfway through.
![screenshot_20170730035706](https://user-images.githubusercontent.com/30566707/28751705-b8361cc4-74dc-11e7-9b0a-ba67d78f7812.png)
I left the settings the way they were including unticked ADX Audio.
Previous installer worked.

**Comment by PiKeyAr** [comment]
Does it jump straight to that error or does it ask you to retry the download first?

**Comment by Omega247Gamma** [comment]
At first, the green bar moves to the right and I can see files installing and appearing in my sonic.exe directory. Then when green bar reaches toward the middle, it gives me the error popup the same time when I'm up to the "Downloading DirectX Setup (~300KB)..." part and installation process stops from there. I just did a clean install on steam and tried it on my (C:) directory but no luck.

**Comment by PiKeyAr** [comment]
Alright, I see. Seems like the value comparison for the download plugin I'm using fails for some reason.

Here's a test version that uses a different kind of comparison, also it should give you a more verbose message if it fails again. Please let me know if it fixes the problem. https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/sadx_setup_hf.exe

To test the download part specifically, delete the "data" folder before running the installer to remove the files it may have downloaded previously.

**Comment by Omega247Gamma** [comment]
Data folder is fine. I figured it out and it's an embarrassing one... Oops!

Do not place sadx_setup.exe into the same directory as the game next to sonic.exe.
Place and run sadx_setup.exe elsewhere like on the desktop area. It completes installation. Test game, so far so good!

Wait... There seems to be no ocean when running directly from sonic.exe, even though everything already updated.
![screenshot_20170730093030](https://user-images.githubusercontent.com/30566707/28753998-b09dbfde-750a-11e7-916f-38c806baa7f0.png)

Water texture appears to be there when I hit save & play from the mod manager, but running through sonic.exe remains to have the same waterless Emerald Coast.

EDIT: Also fixed! Verified all the files in mod manager. Turns out Dreamcast Station Square failed to verify 1 file I can't tell which file it is, but that fixed it. So no more missing water in Emerald Coast when running through sonic.exe itself once verified.

**Comment by PiKeyAr** [comment]
Oh, sorry about that. I built the DC_Levels archive from my current SADX mods folder, which contains some changes I haven't pushed to the public yet. I'll update the archive to make sure the files match the manifests.

As for running the setup program from the SADX folder, I can't immediately see why it would fail to download things, I'll have a look. But yeah, the intended way is to run it from elsewhere.

**Comment by Omega247Gamma** [comment]
With the most recent version, tried it all again and can confirm it works. I can no longer reproduce the glitch. So then I opened mod manager (first time) and verified everything = all pass.

**Comment by Omega247Gamma** [comment]
1) After going through many tests to make sure, once again, I am wrong about the reasoning of the waterless glitch. Glitch has nothing to do with the sadx_setup.exe being in the SADX Folder, although I'd still recommend running installer elsewhere like on desktop.

Here is a video of me using the installer on the desktop area right. This was right after a clean installation of the steam version:

https://sendvid.com/0gw9fwny

^ After installation, mark 2:00 demonstrates the random behavior of waterless glitch. Sometimes it works, sometimes it doesn't.

Well, I won't say if this is the 100% reasoning behind the issue, but I think it makes sense. The order in mod manager is not in the same order as in DC Conversion folder.
![screenshot_20170731074631](https://user-images.githubusercontent.com/30566707/28781005-a8600a44-75d6-11e7-97b0-2f25770629a5.png)

I then put the DC Conversion mods in order like the order in DC Conversion folder.
![screenshot_20170731080201](https://user-images.githubusercontent.com/30566707/28781007-aa80af18-75d6-11e7-8c3b-f400e8c1dcd2.png)

Out of 20 retries, I haven't been able to reproduce it ever since I made the right order.

2) The Rhinotank has visible texture while it moves.
![untitled](https://user-images.githubusercontent.com/30566707/28781254-75b706dc-75d7-11e7-9397-931b690d159a.png)

When I turn off SADX:FE in mod manager, Rhinotank wheels are black during movement like Dreamcast.
![untitled2](https://user-images.githubusercontent.com/30566707/28781283-95f5bf88-75d7-11e7-899f-37172eddc07a.png)

**Comment by PiKeyAr** [comment]
I don't think the mod order itself has anything to do with this, but it may be triggering a race condition that causes it. The mod order set up by the installer is the recommended mod order.

I've introduced a workaround in the Emerald Coast mod so hopefully it won't happen anymore.

**Comment by Omega247Gamma** [comment]
So I reinstalled again, ran sadx_setup.exe on desktop, then launched the game.
I haven't reproduced it in more than 20 attempts...
Then made sure the mod manager was ok. Everything is already updated with all verification passed.

The Rhinotank tire texture thing is still different when I have SADX:FE enabled.

**Comment by PiKeyAr** [comment]
Thanks for testing! Also I think you've answered your own question, the rhinotank texture thing is a feature of SADXFE.

**Comment by kazuya44** [comment]
so FE should be enabled even with the conversion mod ? Also I notice that the shadows that DX added arnt available when I use the conversion and lighting mod.  Is that because Iam not using newest visual ++ and other files  ?

Thanks for the launcher all the same

**Comment by PiKeyAr** [comment]
If you mean SADXFE, it isn't required for DC Conversion, but it's a popular enough mod to be included in the installer, and some of the fixes I have in DC Conversion will eventually be moved to SADXFE. To put it simply, if you want just the DC stuff you don't absolutely have to have SADXFE, but if you want some general fixes that don't deal specifically with Dreamcast assets (e.g. SEGA voice or auto camera fix), you can use SADXFE. It's compatible with DC mods as long as you put it at the top of the mod list in the Mod Manager.

As for the SADX shadows, those are baked into SADX levels (vertex colors + sometimes transparent models). They don't exist in SA1 levels because SA1 used a different lighting system. It would be really tedious to copy the shadows over to SA levels because you'd have to go through each SADX landtable piece, match it up with the SA1 counterpart and copy over the vertex colors. It's potentially doable, but it would take a lot of time and it's a bit outside the scope of what the Dreamcast mods do.

**Comment by kazuya44** [comment]
Oh I see, also the reason I mentioned the shadows because on Sonic Retro when they first talked about it, they showed the DX shadows with the lighting mod so I assumed they where being used with your conversion. Thanks for the info

**Comment by PiKeyAr** [comment]
Oh yeah, you can use the lighting mod without Dreamcast level mods, the shadows will be back but texture quality, fog, level layout, level effects (such as environment mapping) and object models will be the same as unmodded SADX.

**Comment by kazuya44** [comment]
I tryed that and noticed that those shadows added to DX dont really cast on the characters regardless so they look more fake the more I see them, and I can see that the textures from the conversion are  better or at least mostly as they are more colorful, always thought DX would have better textures as the game was newer. Iam guessing the DX textures are higher resolution though arnt they ?

**Comment by PiKeyAr** [comment]
I know at least one stage where SADX textures are of higher resolution, which is Red Mountain 1, however I think in most cases the resolution is the same between SA1 and SADX. Many textures in SADX are badly recompressed Dreamcast textures. Also the PC version actually has many textures in lower resolution than Dreamcast and Gamecube due to texture mirroring. In general, the PC version has the lowest texture quality caused by mindless conversions between texture formats during Dreamcast->Gamecube->PC porting.

The original Dreamcast game was made in such a way that it was difficult to replicate on other platforms. I highly suspect the reason behind most visual changes in SADX has to do with the problems the developers ran into when using the original assets. The majority of graphical "improvements" in SADX appear to be poor attempts to avoid or mask the rendering problems involving transparency, and to camouflage the removal of the palette lighting system. You can read up on this more in the Dreamcast mods topic on Retro if you're interested.

Anyway this is going a bit offtopic and I'd like this issue to focus on the mod installer if you don't mind.

**Comment by kazuya44** [comment]
should of known this port would be lower quailty, a lot of computer ports back then where similar to that. Regardless, your launcher worked fine for me, no other issues to talk about.

**Comment by PiKeyAr** [comment]
Will reopen if there's more discussion or when a major update drops.

**Comment by cheatfreak47** [comment]
As mentioned on the IRC, this could potentially outright replace BetterSADX entirely (which is certainly on the table, this installer is already really quite good) 

With the addition of a few setup-simplifying changes and maybe a couple additions, this software would have no trouble effectively replacing BetterSADX entirely. I'd be glad to actually even push this on the BetterSADX steam group and formally discontinue BetterSADX itself if things change a bit.

One of the cornerstones of BetterSADX is that people like to be able to open an installer, click next a few times, and wait for the awesome to happen, configuration is great but having a method that is really lazy is also good.

The way I recommend this is through a sort of "presets" system for installation, sort of based on what BetterSADX does. This would skip over any step that the preset defines itself, and possibly includes some configurations for specific mods, such as SA1_Chars, DC_Casinopolis, and DC_Branding.

Some ideas for possible Presets:
### Definitive Sonic Adventure Install
This would include everything that makes the game good, all the bells and whistles. ADX Music, ADX Voices, Dreamcast Conversion, HDGUI, Sound Overhaul, SADX Fixed Edition, etc. This would be approximately what the default installation is now with _literally everything ticked_, but maybe with a couple more mods added to bring the feature set up to snuff with BetterSADX.
 - SonicFreak94's Idle Chatter (because why not?)
 - MainMemory's Egg Carrier Ocean Music (a bit subjective but I think it's an improvement)
 - A mod that doesn't exist yet that swaps the order of the music during the Perfect Chaos boss fight.
 - Super Sonic, maybe? 

Off-topic, Super Sonic is still a weird one for me. I want it to be there, but I also want it that mod itself to have some additional features that make it so it can be configured to behave even more like an in-game unlockable, comparable to how Super Sonic is done in modern Sonic games. Plus more fixes so Super Sonic hovers over water properly in Emerald Coast and Lost World's Snake Room, etc. It just needs work.

### Definitive Sonic Adventure DX Install
This would be reserved for mods that only _improve aspects about the DX version of the game_, rather than completely reverting to the Dreamcast Conversion. While DX is irrefutably worse, people grew up with it, people like it, so we've gotta have an option for those people. Several new mods would probably need to be added and/or made to make this option viable. Possibly maybe sadx-gc-lighting could go here eventually.

### Minimal Install
In BetterSADX, we offered an option that does the bare minimum needed to get the game running the SADX Mod Loader without any feature being missing. It should also include the speedrun approved mods. (Xinput-Fix, Camera Code Error Fix, and Frame Limiter) While not necessary, it'd still be nice to have this as an option for those that want to get into Speedrunning SADX and can't get ahold of a legit 2004 copy.

### Custom
This would be chosen to move into the comprehensive configuration options setup you already have implemented. This would allow for in-depth tweaking of the install, through and through, possibly with additional options from stuff added to suit the presets.

This is all just conjecture of course, but I figure it's not invaluable as feedback, so here it is, I'll probably keep maintaining BetterSADX in the meantime but if you ever want to push this software as a replacement for BetterSADX, that's my two cents on how to go about it.

**Comment by PiKeyAr** [comment]
I've been considering a profile-based setup for a while, so maybe it's time to flesh it out now. Here's a new beta build of the installer. It introduces a much improved update system and a profile-based setup similar to what you've described.
https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/sadx_setup2.exe
As this build isn't officially released yet, it will detect the difference with the official build and assume an update for the installer is available. Until it's released, allowing it to self-update will downgrade it to the official version, which uses an older implementation of the update system, so it's better to ignore the self-update prompt.
My only problem with this replacing BetterSADX is that I don't have any way of interacting with the BetterSADX userbase, which seems to stay mostly on Steam forums. I'm not planning to start using Steam anytime soon, so I can't write Steam guides, make announcements there, respond to feedback on forums etc. If BetterSADX users were to migrate to my installer, some solution for this would be necessary.

**Comment by PiKeyAr** [comment]
I have released a new version of the installer along with an offline package on ModDB.
[Release post](http://www.moddb.com/mods/sadx-dreamcast-conversion/news/vote-for-dc-conversion-on-moddb-massive-installer-update)

**Comment by PiKeyAr** [comment]
Will reopen when a new major release drops or if there is need for more discussion.

**Comment by cheatfreak47** [comment]
As you're probably aware I've long since dropped support for BetterSADX myself and while Carlmundo is continuing to maintain it himself, as far as I can tell, he's not really putting in the effort.

Anywho, I was popping in to ask if/when you plan on including HDGUI Prompts as an option in the installer (Ideally a page where they pick from a dropdown what button prompts the game should use)

And also, if you would add a checkbox to have DiscordSADX as an optional download, since it was always my goal to make that a standard mod for discord users.

I think we discussed this on IRC ages ago but I've been busy with other things for quite some time.

**Comment by PiKeyAr** [comment]
I've added a "More mods" link to the final page of the installer, which leads [here](https://dcmods.unreliable.network/sadxmods/). The content on that page is currently just a placeholder. I intend to replace it with a functional catalog with 1-click install links, previews, descriptions etc. Maybe even with an option for people to upload their own mods. However, all that will be done on the server side, not in the installer itself. The link will remain the same after the update.

**Comment by bejeweledman** [comment]
I've tried to install the mod loader to convert my steam version, however it pops up this error message.
I'm double checked the steam directory and it's correct. Would you please provide the solution to fix this? Thank you!
![error](https://user-images.githubusercontent.com/63660575/79247628-59d82180-7ead-11ea-8ffe-2d9dff7c7ad3.png)

**Comment by PiKeyAr** [comment]
This message shows up when the installer can't find several files specific to the either version that should be there. If you have deleted any files in your SADX folder, recheck integrity on Steam.
Is your executable named Sonic Adventure DX.exe?

**Comment by bejeweledman** [comment]
Yes, the executable is named Sonic Adventure DX.exe.
I've checked the file integrity on Steam, it repaired but the error message still pops up. Here is the file directory's screenshot. Do I need to rename any of the files?
![screenshot](https://user-images.githubusercontent.com/63660575/79285450-2cf92e00-7ef0-11ea-852e-4362a15e6b8f.png)

**Comment by PiKeyAr** [comment]
The installer uses the name of the executable to determine which version of the game is installed. You have both sonic.exe and Sonic Adventure DX.exe in the folder. Since the installer checks for the 2004 version first, it assumes you have the 2004 version because of that. You need to delete or rename sonic.exe for it to detect the game's version correctly.
Also I'd recommend putting the sadx_setup.exe in a folder other than the game's folder, though this shouldn't cause problems per se.

**Comment by AlexField442** [comment]
When I use the installer (on Steam), the FMVs won't load and nearly all the audio (barring a few voice clips) is missing. Help?

**Comment by PiKeyAr** [comment]
The FMVs should always be in the system folder. The videos may not play for three reasons: 
1) Windows Media Player components are missing - this can happen if you have the "N" version of Windows installed.
2) SADX 2004 may not like certain video codecs you have installed, particularly ffdshow and LAV.
3) The installer has failed to convert the videos from SFD to MPG.

The audio could be missing for several reasons. I need to know what your system\sounddata folder looks like before I can tell what happened. It's possible that the sounddata folder wasn't moved to the system folder, or that the installer failed to convert the soundbanks to the format used by SADX 2004. If the music is also missing, it's likely that the whole sounddata folder is in the wrong place. If it's in SADX main folder, move it to the system folder.

File conversion and other file operations may fail due to interference from an antivirus or because the program or your SADX folder doesn't have the necessary permissions, though the installer tries to take care of that so it shouldn't be the case. It may also be an issue with the conversion script. From the sound of it it seems like the scripts to convert audio and FMVs didn't execute correctly.

**Comment by PiKeyAr** [comment]
The Mod Installer is now open source and it has its own issue tracker: https://github.com/PiKeyAr/sadx-mod-installer/issues

**Comment by rita-belli** [comment]
hi! everytime i try to install the mods with the program this message pops up (after a window asking me if i wanna retry the download)
it tells me to use the offline version even tho im using that one, do i have to put the InstData folder in a specific folder?
![error](https://user-images.githubusercontent.com/98564955/151467247-f1f89584-c017-4c33-86c6-64189fb82238.png)
hi! everytime i try to install the mods with the program this message pops up (after a window asking me if i wanna retry the download)
it tells me to use the offline

**Comment by PiKeyAr** [comment]
The installer only downloads files if they are missing in the instdata folder. The most likely reason is that the instdata folder is missing, or some files in it were deleted after checking for updates in the program. The instdata folder should be in the same folder as the installer's EXE file, like in the archive for the offline version.
Even with the folder missing it should still be able to download, though. The SendRequest error is usually related to a certificate mismatch. The certificate on the server is fine at the moment, so it is something you will need to figure out on your end.

**Comment by PiKeyAr** [comment]
Extract the archive again and don't check for updates in the installer.

**Comment by PiKeyAr** [comment]
For further discussion of the mod installer, use this issue tracker:
https://github.com/PiKeyAr/sadx-mod-installer/issues
