### ISSUE TITLE
Lighting problem in Final Egg Act 3 and Orange Gloves

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#173]
So, I noticed a small thing.
![lighting and orange gloves](https://user-images.githubusercontent.com/26051785/36346146-bbaa6c18-13fe-11e8-8f01-2d41209b179e.PNG)
Dreamcast left, SADX right. The lighting on those landtable pieces is somehow inaccurate, and the gloves on the Tails target are orange instead of white.

Edit: Actually...
![uhhh](https://user-images.githubusercontent.com/26051785/36346248-887d97a0-1400-11e8-9ef5-3ec4da85cabe.PNG)
It seems the ignore lighting flag somehow got screwed up.

![eyes](https://user-images.githubusercontent.com/26051785/36346258-bf2dcc0c-1400-11e8-897a-1d8eb6ac2e6b.PNG)
Big's eyes seem to be fine, though.

![trees](https://user-images.githubusercontent.com/26051785/36346278-21645094-1401-11e8-8e8c-a091f3773fc3.PNG)
Seems like it only broke for some things.

And, um, unrelated, but  could you please not disable item box rotation if the SET Fixes mod is off? At least make it a toggle? It's annoying.

**Comment by PiKeyAr** [comment]
That was a white diffuse palette thing not working correctly. The models don't ignore lighting, but they have a white diffuse palette as a side effect of how the lighting system in SA1 works. I restored it for the sake of accuracy, but it broke in some levels after the switch to the unified mod structure. Should be fixed in the next update. The color on the gloves was another material color issue present in SADX, should also be fixed in the next update.


I have no plans to re-enable item capsule rotation specifically when SET fixes are turned off. The reason I implemented it this way is that the original game doesn't have item capsule rotation, and turning it on breaks item capsule rotation when the unmodified SA1 SET files are used. Item capsule rotation is something SADXFE added as an experiment, i.e. it was never a feature of the main game. If your mod needs item capsule rotation, you could just keep SET fixes enabled and disable the level you're replacing in the config. Having SET fixes on should have no effect on the replacement level if its Dreamcast counterpart is disabled in the config.
