### ISSUE TITLE
SADX Water Effects

### ISSUE THREAD

**Issue by Shadowboxer2005** [PiKeyAr/sadx_dreamcast#200]
In the GameCube version of SADX had some extra water effects, which includes.
- A water ripple effect for underwater objects.
![gxse8p-8](https://user-images.githubusercontent.com/43715619/49000398-8a7ec480-f1ad-11e8-8737-71af4c0db45a.png)
- An effect showing the reflection of an object.
![gxse8p-10](https://user-images.githubusercontent.com/43715619/49000415-9c606780-f1ad-11e8-9963-4933607060be.png)
Is it possible to add it?

**Comment by Shadowboxer2005** [comment]
Wow i'm issue #200.

**Comment by PiKeyAr** [comment]
These water effects were done using a texture manipulation system (TEV) exclusive to Gamecube hardware, though it's possible to create a similar looking effect on PC using a shader. I'm also interested in this kind of distortion effect because it would help me implement a better solution for the ripples on the title screen.

I'm not knowledgeable enough on how to inject shaders in SADX though, and this particular variation of distortion is outside the scope of what Dreamcast Conversion does. However, I did some initial research on this effect [for the Lantern Engine mod](https://github.com/SonicFreak94/sadx-dc-lighting/issues/15), which also uses shaders. As this is about all I can offer, it's up to @SonicFreak94 to implement a working shader for it.
