### ISSUE TITLE
Dreamcast Inconsistencies/Fixes

### ISSUE THREAD

**Issue by Shadowboxer2005** [PiKeyAr/sadx_dreamcast#201]
In in Egg Walker fight the billboard is "The Man 3" due to it being an earlier map.
There's a few unused areas which used to be entrances to the stage, this includes.
1. Dilapidated Way (Casinopolis 2)
2. Final Egg 1 (Used in AutoDemo)

**Comment by PiKeyAr** [comment]
These are indeed interesting inconsistencies that have been documented previously.

While these differences would be fun to tackle (I heard ItsEasyActually wants to work on an Autodemo conversion mod), Dreamcast Conversion is not meant to address them. With a couple exceptions (like the Cowgirl from the Japanese version, which was big enough of a curiosity and requested by a lot of players), the mod's main objective is to restore assets from the final US version of the Dreamcast game.

This means I am not interested in fixing inconsistencies and design flaws that were in the original Dreamcast game, unless they cause noticeable visual issues and are fixable within the limits of my modding knowledge.

When submitting bug reports or feature requests, please refer to the section "About issues with original SA1 gameplay/aesthetics" in [this guide](https://www.moddb.com/mods/sadx-dreamcast-conversion/tutorials/troubleshooting-and-bug-reporting-guide).

**Comment by Shadowboxer2005** [comment]
I'm about to upload a mod that fixes 2 bugs.
* Purple Hint Boxes
* The Man 3

**Comment by Shadowboxer2005** [comment]
Download here!
https://gamebanana.com/gamefiles/7995

**Comment by PiKeyAr** [comment]
Dude... What?

I have no comments on the poster thing, but the purple hint boxes were a feature of a very old build of DC Conversion from over a year ago. The current version of the mod doesn't have them. The purple hint boxes in the old mod were achieved by altering the hint monitor model's material color in code. Editing the palette files wouldn't have any effect on that. Your "fixed" PL file (which is in fact the same file that comes with Lantern Engine) doesn't have a palette I added to imitate the effect when the lights go out before Eggman's appearance in front of the E Series in Gamma's story. So if your file was loaded together with DC Conversion, the effect wouldn't work correctly. However, your PL file wouldn't even be loaded in the current version because in that stage DC Conversion loads a custom PL file with a different name (PL_W1X.BIN).

I mean, I have no issue with you trying to patch up things I'm not interested in, but your "fix" makes no sense.
