### ISSUE TITLE
Strange Robot Monkey Placement in Emerald Coast

### ISSUE THREAD

**Issue by sa-nd** [PiKeyAr/sadx_dreamcast#213]
So...  This isn't something that happened with the latest beta release, rather it's a problem I've always seen when using the dreamcast conversion mod.

![20190813133701_1](https://user-images.githubusercontent.com/52898048/62996884-460a8600-be1b-11e9-9d90-a1cc7c6c9b92.png)
![20190813133822_1](https://user-images.githubusercontent.com/52898048/62996885-460a8600-be1b-11e9-95f3-505659761c0e.png)

They're just not quite standing on the trees are they...
When I turn the mod off, it looks like this
![20190813205346_1](https://user-images.githubusercontent.com/52898048/62996945-73573400-be1b-11e9-80c3-7c78e00ea57f.png)
![20190813205642_1](https://user-images.githubusercontent.com/52898048/62996950-7520f780-be1b-11e9-942c-c6c4668b0412.png)

I don't think that such an obvious problem is universal, or I'm sure it would have been patched, which makes me wonder if it's just me. Although, I do recall seeing videos on youtube, where those people had the same problem (Don't remember which video, that was a while ago, and they weren't showcasing this issue, but another mod, like a character skin for sonic or something.)

It looks like they're using the original coordinates from vanilla sadx, and aren't adjusted for the dreamcast conversion.

Am I missing something here? I'm pretty sure I am, like a single setting that's off or something. I just thought I should report this anyway.

**Comment by PiKeyAr** [comment]
They are like that in the Dreamcast version. You can notice that some palm trees appear shorter in DX, that's because their position was lowered so they are partially underground. I think it's mostly the trees that had the coordinates change rather than the badniks. Since DC Conversion's SET files are based on the original game's SET files, this change isn't applied. While this is [a known difference](https://tcrf.net/Sonic_Adventure_DX:_Director%27s_Cut_(GameCube)/Changes_from_the_Dreamcast_Version#Emerald_Coast) between DC and DX, I don't consider it an issue.

**Comment by sa-nd** [comment]
Hm, alright then, my mistake then.
