### ISSUE TITLE
Missing Speed Highway loading zone

### ISSUE THREAD

**Issue by Oggom** [PiKeyAr/sadx_dreamcast#223]
Hello!

When I was messing around with the mod I've noticed the loading zone for Knuckles' Speed Highway entrance seems to be disabled unless you play as him. In the Dreamcast (tested both US and International releases) and GameCube versions the loading zone is always active regardless of which character you play as. This allows you to enter the level with any character if you manage to cheese your way out of bounds.

On a similiar note, it was possible to enter Speed Highway's Going Down segment with Tails by simply flying through the building. This was possible in both the Dreamcast and GameCube releases but was actually fixed in the PC version. 

Since these loading zones were present in the Dreamcast release and aren't harmful to a casual play-through I believe they should be re-enabled in this mod.

**Comment by PiKeyAr** [comment]
By default, the mod uses optimized SET file layouts that remove duplicate, invalid or redundant items (as deemed by their original contributor), as well as fix Z-fighting with some objects. If you want to use original SET files from Dreamcast versions of the game, change the "SET and camera layouts" setting in the mod's configuration window in SADX Mod Manager. Note that the original SET files aren't compatible with Mission Mode and you'll also need to enable the Light Speed Dash distance hack if you use them.

**Comment by Oggom** [comment]
This setting did indeed re-enable the Speed Highway loading zone, although the Going Down one is still missing.

It seems odd that only the SH one was removed, other loading zones like Emerald Coast and Twinkle Park remain active regardless of what character you play as. It definitely appears to be inconsistent when it comes to that at least.

**Comment by PiKeyAr** [comment]
I'm not sure about the Speed Highway one, but I can tell it doesn't work in vanilla SADXPC either. From a quick look it doesn't seem to rely on a SET item, perhaps it's hardcoded in the game's code. 
As for the stuff seeming inconsistent with SET fixes, I can see why it feels inconsistent. I think it might be a good idea to prevent some characters from going to areas they aren't supposed to visit, especially because some of these glitches aren't as harmless as they might seem - for example, getting Tails in Emerald Coast will corrupt the save file if the game is saved afterwards. So in that sense, it's better to prevent as many of these glitches as possible. Maybe we'll do that someday.

**Comment by Oggom** [comment]
As I said, this really isn't something that can happen on a casual play-through, you have to go out of your way to allow that to happen. It's a fun thing to do if you've seen everything the main story has to offer. People have been doing that ever since the game came out in Japan.

I was under the impression that the aim of this mod was to bring the levels as close to the Dreamcast version as possible. If I wanted one that tries to "fix" the game I'd install SADXFE. Actually, even that mod still allows you to glitch your way into levels.

**Comment by PiKeyAr** [comment]
The option to use 1998/1999 SET files is still there if you want the old layouts with all errors and glitches from the original. So in that sense, you can get as close as currently possible to the original if that's what you're looking for.

The optimized SET files used in the mod by default were contributed by supercoolsonic, who made a lot of other changes to SET files, most of which I consider improvements. While I probably wouldn't have "fixed" it myself, this particular change doesn't bother me enough to go back and undo it - to be honest I wasn't even aware of it until you made this report.

As for the stuff that was already fixed in the PC version like the Goin' Down transition, this certainly isn't something I'd consider reverting in the mod. I'm not interested in finding and altering the game's code to undo bugfixes and reintroduce glitches, even if they were possible in the Dreamcast version.
