### ISSUE TITLE
SADX mod sound not working

### ISSUE THREAD

**Issue by d0n3v** [PiKeyAr/sadx_dreamcast#225]
i downloaded the modd from a youtube channel {  https://www.youtube.com/watch?v=SORYL5J1Heg&t=1093s  } and my sound isnt working properly.  other than that all the graphics look great

**Comment by PiKeyAr** [comment]
There isn't enough information in your report for me to be able to troubleshoot the issue.

**Comment by d0n3v** [comment]
i have the steam version i just downloaded it yesterday, and the voices and music don't come on. there's no cutscene music or voices in the cutscenes  and no music or voices during gameplay, i tried turning mods off and on again to see if that was the issue and i tried adding folders into the sound folder but couldn't manage to get it. idk what's wrong . the only sound that happens are the options menus the different characters say options. and attacking has sound. there is no menus music either

**Comment by PiKeyAr** [comment]
It seems like you system\sounddata folder is missing bgm and voice_us/voice_jp folders. If you still have the SoundData folder from the Steam version, move bgm, voice_us and voice_jp folders to system\SoundData. The 2004 version  (which is what you have since you have the mods working) requires the SoundData folder to be in the game's system folder.

Normally this shouldn't happen because SADX Mod Installer has a tool that makes the necessary changes to the game's folder structure It may fail if the anti-virus is interfering, or due to some other issue I'm unaware of.

If you're still unable to get voices and music back, get the [ADX Audio mod](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/data/ADXAudio.7z).

**Comment by d0n3v** [comment]
thankyou!

**Comment by PiKeyAr** [comment]
I forgot about the log created by the installer that might help determine the root cause of the problem. If you have the file SteamConversion.log in your SADX folder, could you share it here?
