### ISSUE TITLE
Option to switch back to SADX Icecap act 1 dash ring trail?

### ISSUE THREAD

**Issue by Ducky27** [PiKeyAr/sadx_dreamcast#235]
So in SADX in Icecap act 1 after getting out of the starting cave thing you can go south and light speed dash to go to those press a jump panels to take you to act 2. However in the dreamcast conversion mod at the end of the light speed dash it launches Sonic up in the air and I have to move him a bit forward and to the right to be able to land on the platform without falling off. I hate this so much. I definitely prefer how this is handled in SADX and if there was an option to switch back to how it was then i would like it.

**Comment by Ducky27** [comment]
Just to clarify for this I don't want to change any other dash ring trails just this specific one at the start of icecap

**Comment by PiKeyAr** [comment]
There won't be specific options like that because every change like that would require supplying a different SET file for the stage, and managing that is already difficult with an option to use SET files from two versions of the game besides an "optimized" layout with bugfixes.

However, if this only happens in the mod and not in the original Dreamcast game, this is something that could be looked into for the "optimized" SET layouts.

**Comment by PiKeyAr** [comment]
I've checked the files and it seems like that trail was changed by supercoolsonic in the optimized layout. I've reverted the change to make it like the original game.
