### ISSUE TITLE
Fog is missing from levels

### ISSUE THREAD

**Issue by shadowstardx** [PiKeyAr/sadx_dreamcast#244]
Hello, not sure if I'm doing something wrong or if the lantern engine broke something, fog is missing from levels since the last update. not sure what happened to windy valley act 3 and red mountain 2. custom fog isn't working either. Not sure why the superior dx water textures are gone also. nobody is releasing a general mod loader order so I'm confused.

**Comment by shadowstardx** [comment]
Missing fog didn't have to do with the lantern engine or other mods, Dreamcast conversion removed or broke something.

**Comment by PiKeyAr** [comment]
Thanks for the report. The fog issue should be fixed in the latest update.

>Not sure why the superior dx water textures are gone also.

Assuming you are referring to SADX Style Water, it was removed and is now available as a separate mod that works with and without DC Conversion.


>nobody is releasing a general mod loader order so I'm confused.


Some of the common mods are automatically sorted in the recommended order when you use the SADX Mod Installer. There cannot be a general mod list because there is no way to keep track of all mods being released and their compatibility.

**Comment by shadowstardx** [comment]
thank you for everything and sorry if I came off as a little rude, something about Sonic always brings the worst and best out of humanity lol. Can you link me to the SADX water mod?

**Comment by shadowstardx** [comment]
i found the water textures, thank you for everything. personally, I think some of the ideas dx had were really good. too bad sonic team destroyed the PC ports of their only good games
