### ISSUE TITLE
Incompatibility with Enhanced Emerald Coast

### ISSUE THREAD

**Issue by connor-k-wilson** [PiKeyAr/sadx_dreamcast#261]
It appears that the latest update to Dreamcast Conversion does not work when Enhanced Emerald Coast is also installed, regardless of load order. When I have both active, none of the Dreamcast textures or layouts work, and default to the DX versions. In addition, the star textures for the springs and checkpoint posts become bugged and don't load properly. When only one mod or the other is active without the other, each works correctly and without any issue.

p.s. I noticed while posting this that the original Enhanced Emerald Coast repository isn't on here anymore, so I don't know if that is related in any way

**Comment by connor-k-wilson** [comment]
note, just incase more info is needed: 
-EEC works fine with both mods active, DCC is the only one that stops working
-When both mods are active, I have Emerald Coast turned *off* in the config menu of DCC

**Comment by PiKeyAr** [comment]
The Enhanced Emerald Coast mod is not compatible with Dreamcast Conversion. There used to be a check in DC Conversion's initialization code that disabled the mod and displayed a warning if this mod was detected, but it was removed in a recent update because the Enhanced Emerald Coast mod has been superseded by the SADX Style Water mod, which is compatible. The Enhanced Emerald Coast mod is no longer in development and its repository has been removed.

**Comment by connor-k-wilson** [comment]
I see, thank you for the update! I appreciate the swift response!
