### ISSUE TITLE
Speed Highway (Knuckles) Transparency Issue with Emerald Shards

### ISSUE THREAD

**Issue by Sonikko** [PiKeyAr/sadx_dreamcast#28]
The emerald shard is not appearing behind the glass.
I can't remember if this happened in the vanilla game too.
![screenshot 2017-01-06 00 14 29](https://cloud.githubusercontent.com/assets/24740235/21741748/123b9430-d4e0-11e6-9a2d-f43ea251793a.png)
![screenshot 2017-01-06 00 14 30](https://cloud.githubusercontent.com/assets/24740235/21741749/123d1382-d4e0-11e6-8f43-2c90c196d9b4.png)

**Comment by PiKeyAr** [comment]
Which version of the Speed Highway mod do you have installed?

**Comment by Sonikko** [comment]
The 31st Dec update. Is there a new version? I checked ModDB and Retro and couldn't find anything besides the updated SkyDeck.

**Comment by PiKeyAr** [comment]
Try this one I just built: https://www.dropbox.com/sh/rg79ms8h4rdv19h/AAC_VtLWoRIzD9pJxugIsSmna?dl=0

I used a last-resort workaround to make sure everything gets displayed behind that glass. The glass is slightly brighter as a side effect, but otherwise it should work fine. I can't get the game to spawn an emerald shard in that spot, though I've been able to see the shield behind the glass, which means it should be working.

**Comment by PiKeyAr** [comment]
Updated the mod again. If ModLoader reports version 0.972 for Speed Highway, then you're up to date.
This version should fix all those transparency problems, but I haven't tested it too thoroughly. Please report any issues here.

**Comment by PiKeyAr** [comment]
Unfortunately I won't be able to fix the flickering, as it's caused by something else and happens in unmodded SADX as well. The invisible emerald piece issue should be resolved, though.

**Comment by Sonikko** [comment]
The objects are now showing behind the glass, but I can't seem to get the emerald to spawn there again, but I'd say it's fixed!

**Comment by PiKeyAr** [comment]
Apparently there was another area that could be affected by this. I fixed it in DC_SpeedHighway version 0.975.
I've also tried to adjust material colors so that the affected windows don't look too bright and jarring. I think it worked quite well.
![b2](https://cloud.githubusercontent.com/assets/23312549/21959435/32c2f81c-db0a-11e6-8a04-89450303cec1.png)
