### ISSUE TITLE
Dash Pad nerf during Whale Chase [Emerald Coast Act 1]

### ISSUE THREAD

**Issue by MichaelRichy** [PiKeyAr/sadx_dreamcast#33]
During the part where Sonic gets chased by the whale, I've come across that the dash panels push Sonic slower than normally to a point where the whale actually hits you while some delay in running at odd times. Normally, other characters like Amy can get past 75% of the whale chase part, but with dash pad nerf, even she is not able to get past 25% of the whale chase.

How To Resolve: When removing SET0100S.BIN from mods\DC_EmeraldCoast\system folder, the speeds of the dash pads at whale chase are back to normal (significantly faster without any delay in running away from the whale, like the Dreamcast).

**Comment by PiKeyAr** [comment]
Does it happen with [the original Dreamcast SET file](https://www.dropbox.com/s/cky9bselglphmqs/SET0100S.BIN?dl=0)?
If it doesn't, it's likely related to SADXFE fixes I integrated earlier. I may need to undo them.

**Comment by MichaelRichy** [comment]
Hello there! I just tested the original Dreamcast SET file and the dash pad speed nerf still happens.
Not sure if this helps, but I then took the original Dreamcast SET file out of Sonic Adventure DX\mods\DC_EmeraldCoast\system, and also took out the one in Sonic Adventure DX\mods\SADXFE\SET\system, so I can test the one from main directory (Sonic Adventure DX\system). Interestingly, the speeds of the dash pads are a little faster but have a little slowdown at the end of the first part. So the set in SADXFE folder tend be the fastest at dash pads like in real Dreamcast version without Sonic slowing down.

Here's a video comparison: https://sendvid.com/4no0i78f

**Comment by PiKeyAr** [comment]
Thanks for the comparison video.

Well, I checked my video playthrough of Emerald Coast I still have back from the time I had an actual Dreamcast, and it turns out that it's working as intended.

The footage you provided is not from the real Dreamcast, it's from an outdated emulator that has known control issues with SA1.

Have a look at a playthrough on the actual Dreamcast like [this one](https://youtu.be/qnNTj0zwMFU?t=58) to see what I mean.

**Comment by MichaelRichy** [comment]
Right, I recorded it from NullDC because I don't have any capture card for my real Dreamcast system. I still stand by my statement in labeling it "real", mainly, because of the fact that both real and emulation of SA do indeed skip the 3rd dash pad as well, while speeds of the dash pads are 98% identical with no slowdowns:
https://sendvid.com/0vlidp7v

After the 8th dash pad, however, Sonic will slow down by alot. There was a time where I got hit by the whale as Sonic, although I was able to trigger the hit and death three times: https://sendvid.com/jmd7cdvr

I guess it's no biggy when playing normally, but the nerf still seems a bit... weird imo. Kind of a bummer for characters like Amy who don't usually have a problem getting past: https://sendvid.com/obfnjoj6

At the very beginning I tried opening SETS with tools like SALVL so I can edit them but end up getting unexceptional error. Yikes! Oh well.  I guess this shall be closed now. Thank you (so much) for the restoration and reply! Still worth.

**Comment by PiKeyAr** [comment]
I recommend Demul as it's much more accurate graphics and sound wise, though it still has control issues with SA1 and SA2.

Well, I mean I'm not against this kind of "fixes" in principle, but in this situation it's a bit complicated. It's really hard for me to see the difference with Sonic, and I personally wouldn't call it "nerfing" for Amy, since you're making the comparison using a character that isn't supposed to be there normally, and you'd still have a lot of trouble trying to get past that section even with the "fix". I don't really see the point of it all.

The fact that it happens with the DC SET file indicates that the issue (if there is one, that is) isn't with the SET files, it's with how the game handles controls. Supposedly the Dreamcast version was a bit slower (and the characters were faster) and ignored control for a longer period of time.

Also, I talked with the author of SADXFE and he told me he was planning to either tone down the acceleration or undo it entirely, so you might want to keep that SET file around just in case.
