### ISSUE TITLE
Ice Cap Icicle & Skydeck Fence + Platform Texture

### ISSUE THREAD

**Issue by Flash2k17** [PiKeyAr/sadx_dreamcast#36]
Posting on both pages.

Ice Cap Icicle has different color.
http://screenshotcomparison.com/comparison/199783

Fence seems to ignore lighting (?)
There is a different looking texture on platform.
That ceiling crane thingy has different position of texture (?)
http://screenshotcomparison.com/comparison/199782

**Comment by PiKeyAr** [comment]
Thanks for the report!

1) I have disabled the alpha on the icicle and now it looks brighter and closer to the original. For 100% accuracy a palette selection method needs to be implemented on the sadx-dc-lighting side.
2) I have restored Dreamcast models for the crane and some platforms that had different texture mapping.
3) I have removed the "ignore lighting" flag on some materials to make the rails look closer to the Dreamcast version; however, there seems to be several cases when the rails are brighter in some areas and darker in other areas, which is caused by incorrect palette selection. Again, this is something I can't fix on my end, but I will be able to fix it when sadx-dc-lighting has manual palette selection.

You can get the updated Sky Deck and Ice Cap mods [here](https://www.dropbox.com/sh/gwvgh94qurgq244/AAC6pP52mCz5v6bGM2ageZYOa?dl=0).

**Comment by PiKeyAr** [comment]
I have an idea on how to preserve the icicle's transparency which I'm going to try soon.

**Comment by PiKeyAr** [comment]
Well, the icicle thing is really difficult to fix. I've been able to fix alpha problems with the icicles in Act 1, but Act 2 icicles are problematic. Also they now look less bright again, but that will be solved once I can manually select palettes for level objects.

**Comment by PiKeyAr** [comment]
I have implemented a better solution for the icicles (same link). This is all I can do on my end of things, to make them select the correct (brighter) specular palette some things need to be changed in the PL mod.

**Comment by Flash2k17** [comment]
Awe-in·spir·ing!

**Comment by PiKeyAr** [comment]
Feel free to reopen this if you find anything else.
