### ISSUE TITLE
Accuracy improvements for various levels

### ISSUE THREAD

**Issue by Flash2k17** [PiKeyAr/sadx_dreamcast#41]
Could this be yet another water effect that got wiped off the game?
(1) Notice the ground edges in the water fogged in Dreamcast.
(ignore 2nd Dreamcast pic darkened sides)

http://screenshotcomparison.com/comparison/200263/picture:0
http://screenshotcomparison.com/comparison/200263/picture:1

Off Topic:

Some minor differences between pics.

1st comparison pic
• (2) stretchiness of the wall texture next to the sides of pool doors
• (3) sides of pool doors have bent reflection material in DX
• (4) chairs missing transparency in DX

2nd comparison pic
• (5) stretchiness of the lamppost texture

EDIT: Very sorry for bother but I was comparing this kind of water object in Twinkle Park Act 2 to see if there were any fogginess out of curiousity and there isn't.

But here's what was found between this pic.

http://screenshotcomparison.com/comparison/200272

• (6) Water Brightness
• (7) Red Button Lightness
• (8) Different Kind of Flower Pot Objects (interesting find)
• (9) Background building with the stars on it toward the left also has bit noticeable purple fog in Dreamcast

(lol.. wrote "Twinkle Pack" instead of "Twinkle Park"... oops...)

**Comment by PiKeyAr** [comment]
1. That was a minor issue with alpha sorting, fixed.
2. That texture belongs to the door object (much like 3), so I'm guessing I'll be able to fix that by reimporting the door model. Haven't tried it yet.
3. Same as above.
4. The chairs will look glitchy without order-independent transparency because of the way they're modeled, so the only fix for now is to keep them like that. Nice catch though.
5. Fixed, though I also want to check the lamppost top which always ignores lighting in SADX for some reason.
6. Fixed.
7. That needs to be done on the PL mod's side. See [this](https://github.com/SonicFreak94/sadx-dc-lighting/issues/22).
8. That is mentioned in the known issues file. Same reason as in 4.
9. That's probably just a minor fog distance inaccuracy. I have no way to get the exact fog parameters from the Dreamcast version, so for the most part I just try to make it look similar manually. Not sure if I'll bother fixing this, also note that the angle/position in your comparison is not exactly the same.

Suggestion: please don't use NullDC as it is outdated and can be particularly unreliable with regard to transparent things or stuff looking brighter or darker. Demul is much more accurate.

**Comment by PiKeyAr** [comment]
I have fixed pretty much everything reported here except the objects that need order-independent transparency. See #42 for more details.

Feel free to reopen this if I missed something.
