### ISSUE TITLE
SA1 character models and effects

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#46]
From PkR: At the moment DC Conversion does not include character models (with the exception of some Sky Chase models). There are other people working on Dreamcast model ports, and a separate mod will be released for DC character models when it's ready.
In addition, there are some missing effects, like the motion blur effect on Sonic's feet and Tails' tails, different colors of the spindash trail and the inner layer of the Light Speed Dash glow. Those will also be looked into when the character models are ported.

Original message:
So do you plan to add back the classic run animation only in the Dreamcast version. In the dreamcast version Sonic would have a stretchy foot effect at full speed until light speed shoes are obtained. This effect was completely removed in SADX

**Comment by PiKeyAr** [comment]
I have no plans to do it on my own, however other people are currently working on SA1 character model ports, and they may be able to bring that effect back.

**Comment by Zetchzie** [comment]
Thats awesome I've always missed that effect.

**Comment by cheatfreak47** [comment]
For those curious, this is marked as wontfix because PiKeyAr isn't planning to do this himself on this project.
Intead, ItsEasyActually is working on this with some help from MainMemory.

https://twitter.com/ItsEasyActually/status/832934786050170880

Current progress:
https://pbs.twimg.com/media/C48tKDsW8AIQ0BS.jpg
https://pbs.twimg.com/media/C48tWSbW8AAIJ15.jpg
