### ISSUE TITLE
Right wing segment in Sky Deck 2 doesn't lose it's collision after Breaking.

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#58]
So I was playing Sky Deck Act 2 and I decided to make Sonic jump into the void and something weird happened..... Sonic was still capable of running and walking around on the air where the other segment of the right wing used to be, Here are some screenshots.
(Vanilla DX) Right wing breaking: http://i.imgur.com/7FgZaGU.png
(Vanilla DX) Sonic Jumping into the void (collision of the wing is gone): http://i.imgur.com/bp5Qnjy.png
(MOD) Right wing breaking (not important just for Comparison): http://i.imgur.com/DwwX2Jr.png
(MOD) Sonic is Standing on the Air (Collision is still present): http://i.imgur.com/3REbzTk.png
When sonic Grabs the bars the Right Wing explodes multiple times and it lose it's collision when the animation of this breaking starts.
With the DC_SkyDeck mod the collision of the right wing doesn't disappear so Sonic Can still move around like if the wing never fell off.
By the way I checked the DC version and this doesn't happen, the Collision just disappear when the animation starts as well.

**Comment by PiKeyAr** [comment]
Fixed! There's a function in SADX code that removes the "solid" COL flag from certain items in the COL list, but it got broken because the landtable for Sky Deck 2 was being replaced by the DC mod.

I replaced the function with proper pointers to my landtable and added a check that resets the COL flags if the level is reloaded (after death, restart or leaving it).
