### ISSUE TITLE
EggMobile Texturing Glitch Before Chaos 6 fight (Also Happens in Vanilla DX)

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#59]
I was playing Sonic's story and I noticed another Texturing glitch with the Eggmobile this time During gameplay before Chaos 6 Boss Fight, I wonder if this could be related in some way with #54 because this even happened while playing Vanilla DX of course using the 2004 PC version.
Vanilla DX 2004: http://i.imgur.com/4eXd0im.png
DC Conversion Mod: http://i.imgur.com/JLpUsqc.png
I wonder if this happens on the Steam It would be appreciated if someone checked that out.
Also Here is a Save file Before chaos 6 boss fight on sonic's story: http://www.mediafire.com/file/e5epvfb3e9ip91t/SonicDX03.snc
for anyone who wants see if this happen on his copy of the game.

**Comment by PiKeyAr** [comment]
My guess is that it uses another low-poly model for the Eggmobile in that scene instead of the main one, which loads up later, and they forgot to fix transparency issues in the smaller one. You can see something similar in Big's story before the same fight - there's a low-poly model of Chaos 4 that looks kinda glitchy.

I may be able to fix this if I ever find those models.

**Comment by PiKeyAr** [comment]
Fixed! I was able to locate the glitchy Eggmobile model and found out that EV_EGGMOBLE0.PVM was different between SA1 and SADX. I think the reason this glitch occurs is because of the following:
1) They updated some models of Eggman in the Eggmobile with higher-poly hands.
2) EV_EGGMOBLE0 was among the changed PVMs to accommodate that change.
3) That particular model (Eggmobile NPC model) was not updated, and it is still using a texlist and texture indices from the Dreamcast version.

To fix this, I did the following:
1) Replaced the non-updated NPC model with a higher-poly model used in cutscenes.
2) Replaced the texlist pointer for that model to make it load the texlist for the updated EV_EGGMOBLE0.
