### ISSUE TITLE
Fusion's Chao Editor doesn't detect the game with Dreamcast Conversion

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#60]
PkR's edit: This is caused by the "Sonic Adventure" window title, which makes Fusion's Chao Editor unable to detect the SADX window. You can turn off the  "Sonic Adventure" window title in Dreamcast Conversion settings as shown below:
![image](https://user-images.githubusercontent.com/23312549/39089775-8232b58e-4609-11e8-992f-27c946999e12.png)

Original post:
I use Fusion's Chao Editor to monitor my Chao's stats and what their second evolutions are. Recently, I noticed that when the DC Branding mod is enabled, Fusion's Chao Editor isn't able to detect the game. I think that this is due to the mod renaming the window. Could the window renaming be kept as a separate thing?

**Comment by PiKeyAr** [comment]
Try removing this line from the DC Branding's mod.ini:
WindowTitle=Sonic Adventure

**Comment by LimitCrown** [comment]
Oh. Doing that fixes the problem. Thanks!

**Comment by PiKeyAr** [comment]
Cool! You might want to contact Fusion Chao Editor's developer about this, since custom window titles are now a feature of the Mod Loader, and some other mods may use it as well.

**Comment by PiKeyAr** [comment]
I'm reopening this since I'm going to enable the custom window title again soon. I couldn't find a way to contact Fusion regarding this issue, so if nothing comes up I'll try to reverse engineer the Chao Editor EXE and include a modified version with my mods. Or have a warning about it in DC_Branding.

**Comment by cheatfreak47** [comment]
I've gotten in contact with Fusion once before, I'll see if I can get in contact with him again and forward this issue to him.

**Comment by ChocIce75** [comment]
I had this problem, but I thought that my modified EXE caused it.

**Comment by Galaxy5151** [comment]
A quick fix is to make a small mod which changes the window title back to the original one and placing that mod after the Dreamcast Conversion, which is better than removing the "WindowTitle=Sonic Adventure" line from the Dreamcast Conversion's mod.ini because you don't have to change it after an update.

**Comment by cheatfreak47** [comment]
This is what BetterSADX does already, but it still would be nice if Fusion would fix it.
I actually did make contact with him and he said he will fix it eventually and probably even open source the software, but it may be a while because he's busy.

**Comment by PiKeyAr** [comment]
MainMemory updated the Mod Loader, which now has an API function to set the window title in code. 

I've added an option in Dreamcast Conversion config to disable the "Sonic Adventure" window title. Some time later I'll add an option to do it straight from the mod installer.
