### ISSUE TITLE
Casinopolis machine missing part of the graphic

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#67]
Hi! The new coding and mods are neat, but I noticed something about the transport machine fixes. You forgot to add the "& pinball" beneath "Slot" and "Card", as well as the 7's above "Slot". ...That's it. Everything else works fine.

Oh, but just a quick question. The camera files included in the mods: are they better than the ones SADX has? Are the Dreamcast camera files known to be superior to SADX's?

**Comment by PiKeyAr** [comment]
I just forgot to upload the textures folder for Casino1 on the MEGA/pCloud mirror, which had some textures added for that workaround. Should be working now.

The CAM files on the Dreamcast are known to have different camera angles in some levels; some SADX camera angles were changed for various reasons, at least one such change (Emerald Coast 2) was made to distract the player from draw distance/skybox issues that came up because they changed the skybox scale.
