### ISSUE TITLE
13th list of problems with three screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#96]
I have a couple things to report. Small list, I know, but most of my time has been going into Sky Deck recently.

1. I just saw that super-awesome cowgirl mod you added! Great work! It...even has the sound effect. However, I noticed that the collision for the glass she's holding and her moving arm don't move as the glass and arm move. Same thing for her moving leg. Also, the glass has layering problems with the smoke that pops up from the volcanoes behind it, as well as shields.
![ghost glass](https://cloud.githubusercontent.com/assets/26051785/24128696/8f0dff4e-0dab-11e7-84c3-6c07a85f8d66.png)

2. This part of the cowgirl also has layering problems.
![something wrong with my clothing](https://cloud.githubusercontent.com/assets/26051785/24128763/f6e30376-0dab-11e7-9c79-c6320a63fd52.png)
The white lights around the smoke *also* have layering issues.

3. This piece of clothing appears to be ignoring lighting.
![lighting the night](https://cloud.githubusercontent.com/assets/26051785/24129431/aa514ec8-0db0-11e7-9c86-e17c59293a2a.png)
Or was the entire thing meant to ignore it, to appear more brightly lit?

Were these all problems with the original object? ...Nah. Order-independent layering, right?

**Comment by PiKeyAr** [comment]
You seem to be using an outdated version of the Casinopolis mod. Even though the older version contains support for the Cowgirl mod internally, only version 0.984 or higher is required for it to work properly (this is mentioned in the mod's description). The parts you mentioned aren't supposed to have collision in my implementation, and they aren't climbable. Some of the alpha issues are also fixed in the latest version, though most other things you reported aren't fixable due to the way transparency works in SADX. The current implementation is about as much as I can do with regard to alpha and collision, so I consider it done until another solution comes up.

**Comment by supercoolsonic** [comment]
Oh, I didn't realize the Casinopolis mod also got an update. Sorry about that. All's well and good.

**Comment by Zetchzie** [comment]
be a while the optimized stuff is being uploaded on mega

**Comment by supercoolsonic** [comment]
Oh, is that why I can only see some of them? What's being optimized? I'm curious.

**Comment by Zetchzie** [comment]
Textures are being optimized using oxipng to decrease file size and hopefully improve performance. other than that im not sure

**Comment by supercoolsonic** [comment]
Oohh, that's pretty neat. Sweet. Btw, links are up for the CARRIER3 versions of Act 3 if you haven't gotten them already. MEGA can be a real jerk sometimes...

**Comment by Zetchzie** [comment]
oh ok ^^
